### ISSUE TITLE
(documentation) How long was the ²²Na spectrum taken?

### ISSUE THREAD

**Issue by residualentropy** [OpenGammaProject/Open-Gamma-Detector#59]
Hey, I am investigating using this (awesome) project, but I do want to be able to use the data in the README as reference. If you know how much time the ²²Na spectrum took, adding that information would be greatly appreciated. 

Thanks for your time (and for working on this) :)

**Comment by NuclearPhoenixx** [comment]
Hi there! I just checked and it was a 12 year old Na-22 test source, originally specified at 10 µCi. I recorded this in 30 minutes and had an average count rate of about 520 cps.

Hope that helps!

**Comment by NuclearPhoenixx** [comment]
I'm actually pretty confused now, because the ancient file on my hard drive specifies 10 µCi and 12 years of age, but that would result in a lot less than the 2µCi I wrote in the README. I guess there is something wrong there, either with my past self writing the README or the file info. Either way, it was a 30 minute recording and I'm going to add this to the text 👍🏻

**Comment by residualentropy** [comment]
That's exactly what I wanted to find out, thanks so much for the quick response! :)
